// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20250502053209_a")]
    partial class a
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("ActorDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("ActorImage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1a6b116-4c62-4e52-9604-1ac13e1e6787"),
                            ActorDescription = "Known for action and sci-fi roles.",
                            ActorImage = "keanu_reeves.jpg",
                            ActorName = "Keanu Reeves",
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5955),
                            DateOfBirth = new DateTime(1964, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sex = "Male",
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5956)
                        },
                        new
                        {
                            Id = new Guid("ffc26079-0671-4d1b-8ef6-dfa1a6e2e0c6"),
                            ActorDescription = "Versatile actor in drama and thriller.",
                            ActorImage = "leonardo_dicaprio.jpg",
                            ActorName = "Leonardo DiCaprio",
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5958),
                            DateOfBirth = new DateTime(1974, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sex = "Male",
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5958)
                        },
                        new
                        {
                            Id = new Guid("fd34be32-e1be-4245-aed9-846ae6e4c915"),
                            ActorDescription = "Acclaimed for emotional performances.",
                            ActorImage = "kate_winslet.jpg",
                            ActorName = "Kate Winslet",
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5960),
                            DateOfBirth = new DateTime(1975, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sex = "Female",
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5960)
                        },
                        new
                        {
                            Id = new Guid("e8ef376c-49ad-4e9e-bf74-0bb29776c349"),
                            ActorDescription = "Known for strong action roles.",
                            ActorImage = "carrie_anne_moss.jpg",
                            ActorName = "Carrie-Anne Moss",
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5962),
                            DateOfBirth = new DateTime(1967, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sex = "Female",
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5962)
                        });
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5e624c6-bb43-467d-b7b3-cf644f4761f0"),
                            CityName = "Hà Nội",
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5847),
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5847)
                        },
                        new
                        {
                            Id = new Guid("bd194da6-7d52-4b75-b2e7-adcf17b26e44"),
                            CityName = "Hồ Chí Minh",
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5848),
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5849)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40e8b951-ee7b-4cf5-acdc-368987d7af47"),
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5922),
                            Description = "A hacker discovers a mysterious reality.",
                            Duration = 136,
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            MovieName = "The Matrix",
                            ReleaseDate = new DateTime(1999, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5922)
                        },
                        new
                        {
                            Id = new Guid("b56f7815-3a0e-4c3a-8a01-cb3a83096b0b"),
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5925),
                            Description = "A thief enters dreams to steal secrets.",
                            Duration = 148,
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            MovieName = "Inception",
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5925)
                        },
                        new
                        {
                            Id = new Guid("90837c03-9cac-48fd-8cd9-cc58be9a773f"),
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5927),
                            Description = "A love story aboard a doomed ship.",
                            Duration = 195,
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            MovieName = "Titanic",
                            ReleaseDate = new DateTime(1997, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5927)
                        });
                });

            modelBuilder.Entity("Domain.Entities.MovieActor", b =>
                {
                    b.Property<Guid>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MovieActors");

                    b.HasData(
                        new
                        {
                            MovieId = new Guid("40e8b951-ee7b-4cf5-acdc-368987d7af47"),
                            ActorId = new Guid("e1a6b116-4c62-4e52-9604-1ac13e1e6787"),
                            CharacterName = "Neo",
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5985),
                            Id = new Guid("c7c08bf1-a99a-4585-8472-531b44571f33"),
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5985)
                        },
                        new
                        {
                            MovieId = new Guid("40e8b951-ee7b-4cf5-acdc-368987d7af47"),
                            ActorId = new Guid("e8ef376c-49ad-4e9e-bf74-0bb29776c349"),
                            CharacterName = "Trinity",
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5987),
                            Id = new Guid("a639b8ef-960b-43a1-9d9b-b3754688f5ae"),
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5987)
                        },
                        new
                        {
                            MovieId = new Guid("b56f7815-3a0e-4c3a-8a01-cb3a83096b0b"),
                            ActorId = new Guid("ffc26079-0671-4d1b-8ef6-dfa1a6e2e0c6"),
                            CharacterName = "Dom Cobb",
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5989),
                            Id = new Guid("79d89eab-149b-4de3-a017-25d844cb00f5"),
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5989)
                        },
                        new
                        {
                            MovieId = new Guid("90837c03-9cac-48fd-8cd9-cc58be9a773f"),
                            ActorId = new Guid("ffc26079-0671-4d1b-8ef6-dfa1a6e2e0c6"),
                            CharacterName = "Jack Dawson",
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5991),
                            Id = new Guid("c5af74dd-10af-4916-8e4f-9c7119dff75c"),
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5991)
                        },
                        new
                        {
                            MovieId = new Guid("90837c03-9cac-48fd-8cd9-cc58be9a773f"),
                            ActorId = new Guid("fd34be32-e1be-4245-aed9-846ae6e4c915"),
                            CharacterName = "Rose DeWitt Bukater",
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5994),
                            Id = new Guid("a9a7374c-4d51-4306-8d27-85d958b501bd"),
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5994)
                        });
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("817175b8-73a4-439d-be60-c66f403fbea0"),
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 277, DateTimeKind.Utc).AddTicks(9333),
                            RoleName = "Admin",
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 277, DateTimeKind.Utc).AddTicks(9335)
                        },
                        new
                        {
                            Id = new Guid("26a9bc0d-dc2b-4c2a-8c4e-5dd000aeab0b"),
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 277, DateTimeKind.Utc).AddTicks(9339),
                            RoleName = "Staff Manager",
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 277, DateTimeKind.Utc).AddTicks(9339)
                        },
                        new
                        {
                            Id = new Guid("a035064c-6c42-4836-b0b3-6df0d783ae19"),
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 277, DateTimeKind.Utc).AddTicks(9340),
                            RoleName = "Staff",
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 277, DateTimeKind.Utc).AddTicks(9341)
                        },
                        new
                        {
                            Id = new Guid("0f7b52ba-1255-4a2a-bcbd-e9bc8bfc1515"),
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 277, DateTimeKind.Utc).AddTicks(9342),
                            RoleName = "Customer",
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 277, DateTimeKind.Utc).AddTicks(9342)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("TheaterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TheaterId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Domain.Entities.Showtime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<int>("AvailableSeat")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("ShowtimeDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("RoomId");

                    b.ToTable("Showtimes");
                });

            modelBuilder.Entity("Domain.Entities.Theater", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TheaterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Theaters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("efe6fdcb-285c-4e54-b3dc-15f13ec3a393"),
                            CityId = new Guid("f5e624c6-bb43-467d-b7b3-cf644f4761f0"),
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5878),
                            Location = "Số 1, Phố Ngô Quyền, Hà Nội",
                            TheaterName = "CGV Hà Nội",
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5878)
                        },
                        new
                        {
                            Id = new Guid("7d0e4f1c-a23f-40ac-a7e4-b48e7fdb05ba"),
                            CityId = new Guid("f5e624c6-bb43-467d-b7b3-cf644f4761f0"),
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5881),
                            Location = "Số 2, Phố Trần Duy Hưng, Hà Nội",
                            TheaterName = "Lotte Cinema Hà Nội",
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5881)
                        },
                        new
                        {
                            Id = new Guid("3ffd2193-c4c4-40db-8195-1e91b8a90b7a"),
                            CityId = new Guid("bd194da6-7d52-4b75-b2e7-adcf17b26e44"),
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5883),
                            Location = "Số 10, Phố Nguyễn Huệ, Hồ Chí Minh",
                            TheaterName = "CGV Hồ Chí Minh",
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5883)
                        },
                        new
                        {
                            Id = new Guid("2cc7df46-ddaf-42d1-a2ca-de72d2630650"),
                            CityId = new Guid("bd194da6-7d52-4b75-b2e7-adcf17b26e44"),
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5885),
                            Location = "Số 20, Phố Lý Tự Trọng, Hồ Chí Minh",
                            TheaterName = "BHD Star Cineplex",
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5886)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("ShowtimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("Id");

                    b.HasIndex("ShowtimeId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("Id");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("beac5b1a-415c-4ee2-ab2b-b0ebfc761742"),
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5803),
                            Email = "admin@example.com",
                            IsBlocked = false,
                            PasswordHash = "dGKFpHEqxwmRmxf1eiyukmoVAmkQ2yv0iqYtTy8Wm98=",
                            PasswordSalt = "xgTwBzajWrPs7d/yWyVAVQ==",
                            Phone = "1111111111",
                            RoleId = new Guid("817175b8-73a4-439d-be60-c66f403fbea0"),
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5804),
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("c8155e42-0761-4ca3-9d79-4fadd52fb3a2"),
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5807),
                            Email = "manager@example.com",
                            IsBlocked = false,
                            PasswordHash = "dq1tU9BM0nTL+i8tyx48Ek2sDdUSBW0m6VbhU8f+iWY=",
                            PasswordSalt = "rKeq+ZfhoOf1NLmQLzaQ2w==",
                            Phone = "2222222222",
                            RoleId = new Guid("26a9bc0d-dc2b-4c2a-8c4e-5dd000aeab0b"),
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5808),
                            UserName = "staffmanager"
                        },
                        new
                        {
                            Id = new Guid("9dfe6fd3-fcb4-4403-a94d-07161fe9721d"),
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5810),
                            Email = "staff@example.com",
                            IsBlocked = false,
                            PasswordHash = "YRvSkuRIf7lSOvUnK2plb+PI/P1GYlMMxv3wvDdNvWE=",
                            PasswordSalt = "iIRfptVj1+HGdQVQhlZ22Q==",
                            Phone = "3333333333",
                            RoleId = new Guid("a035064c-6c42-4836-b0b3-6df0d783ae19"),
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5810),
                            UserName = "staff"
                        },
                        new
                        {
                            Id = new Guid("e915fe56-c8eb-4e94-a61b-abd7080b4a54"),
                            CreatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5813),
                            Email = "customer@example.com",
                            IsBlocked = false,
                            PasswordHash = "QsigimfYAOPyn66FbKTvX+NMZkclQLoaGzGJ/S3L7Xo=",
                            PasswordSalt = "pnaoPao0xacbWax0WJd54Q==",
                            Phone = "4444444444",
                            RoleId = new Guid("0f7b52ba-1255-4a2a-bcbd-e9bc8bfc1515"),
                            UpdatedAt = new DateTime(2025, 5, 2, 5, 32, 7, 285, DateTimeKind.Utc).AddTicks(5813),
                            UserName = "customer"
                        });
                });

            modelBuilder.Entity("Domain.Entities.MovieActor", b =>
                {
                    b.HasOne("Domain.Entities.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Room", b =>
                {
                    b.HasOne("Domain.Entities.Theater", "Theater")
                        .WithMany("Rooms")
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("Domain.Entities.Showtime", b =>
                {
                    b.HasOne("Domain.Entities.Movie", "Movie")
                        .WithMany("Showtimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Room", "Room")
                        .WithMany("Showtimes")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Domain.Entities.Theater", b =>
                {
                    b.HasOne("Domain.Entities.City", "City")
                        .WithMany("Theaters")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Domain.Entities.Showtime", "Showtime")
                        .WithMany("Tickets")
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Showtime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Domain.Entities.Ticket", "Ticket")
                        .WithOne("Transaction")
                        .HasForeignKey("Domain.Entities.Transaction", "TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Actor", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Navigation("Theaters");
                });

            modelBuilder.Entity("Domain.Entities.Movie", b =>
                {
                    b.Navigation("MovieActors");

                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Room", b =>
                {
                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("Domain.Entities.Showtime", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Domain.Entities.Theater", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Tickets");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
