// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    partial class MovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("ActorDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("ActorImage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fd2fd92d-f031-4413-9185-70b639486717"),
                            ActorDescription = "Known for action and sci-fi roles.",
                            ActorImage = "keanu_reeves.jpg",
                            ActorName = "Keanu Reeves",
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8391),
                            DateOfBirth = new DateTime(1964, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sex = "Male",
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8391)
                        },
                        new
                        {
                            Id = new Guid("5c56da82-871d-4993-b918-30238918232c"),
                            ActorDescription = "Versatile actor in drama and thriller.",
                            ActorImage = "leonardo_dicaprio.jpg",
                            ActorName = "Leonardo DiCaprio",
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8393),
                            DateOfBirth = new DateTime(1974, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sex = "Male",
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8393)
                        },
                        new
                        {
                            Id = new Guid("f58bd65c-3508-46c3-9eb8-d55ac431db1e"),
                            ActorDescription = "Acclaimed for emotional performances.",
                            ActorImage = "kate_winslet.jpg",
                            ActorName = "Kate Winslet",
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8395),
                            DateOfBirth = new DateTime(1975, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sex = "Female",
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8395)
                        },
                        new
                        {
                            Id = new Guid("71e9e85b-e367-4038-84d6-91cfa8997488"),
                            ActorDescription = "Known for strong action roles.",
                            ActorImage = "carrie_anne_moss.jpg",
                            ActorName = "Carrie-Anne Moss",
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8397),
                            DateOfBirth = new DateTime(1967, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sex = "Female",
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8397)
                        });
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50a7f8e6-5f75-4a46-8cbb-27c3d3860f7f"),
                            CityName = "Hà Nội",
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8277),
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8278)
                        },
                        new
                        {
                            Id = new Guid("bc167d53-29dc-41ae-b8aa-b8c20c1d0ca7"),
                            CityName = "Hồ Chí Minh",
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8303),
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8304)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MovieImage")
                        .HasColumnType("longtext");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c05797db-c6c7-4501-b86b-3279a6101c8b"),
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8363),
                            Description = "A hacker discovers a mysterious reality.",
                            Duration = 136,
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            MovieName = "The Matrix",
                            ReleaseDate = new DateTime(1999, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8363)
                        },
                        new
                        {
                            Id = new Guid("d7dc21e5-f25c-4dfd-a681-ce576bd4cf0c"),
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8366),
                            Description = "A thief enters dreams to steal secrets.",
                            Duration = 148,
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            MovieName = "Inception",
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8366)
                        },
                        new
                        {
                            Id = new Guid("6b216128-bfe7-4e66-987f-2106c724c60b"),
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8368),
                            Description = "A love story aboard a doomed ship.",
                            Duration = 195,
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublic = true,
                            MovieName = "Titanic",
                            ReleaseDate = new DateTime(1997, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8368)
                        });
                });

            modelBuilder.Entity("Domain.Entities.MovieActor", b =>
                {
                    b.Property<Guid>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MovieActors");

                    b.HasData(
                        new
                        {
                            MovieId = new Guid("c05797db-c6c7-4501-b86b-3279a6101c8b"),
                            ActorId = new Guid("fd2fd92d-f031-4413-9185-70b639486717"),
                            CharacterName = "Neo",
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8414),
                            Id = new Guid("1f977863-a473-430b-a5d0-7be79e1faf29"),
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8414)
                        },
                        new
                        {
                            MovieId = new Guid("c05797db-c6c7-4501-b86b-3279a6101c8b"),
                            ActorId = new Guid("71e9e85b-e367-4038-84d6-91cfa8997488"),
                            CharacterName = "Trinity",
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8418),
                            Id = new Guid("393d176e-4f52-4d05-a1f8-b5b42d919df8"),
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8418)
                        },
                        new
                        {
                            MovieId = new Guid("d7dc21e5-f25c-4dfd-a681-ce576bd4cf0c"),
                            ActorId = new Guid("5c56da82-871d-4993-b918-30238918232c"),
                            CharacterName = "Dom Cobb",
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8420),
                            Id = new Guid("94e4c52b-7d44-4fa9-af8e-b5d82efbeb5e"),
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8420)
                        },
                        new
                        {
                            MovieId = new Guid("6b216128-bfe7-4e66-987f-2106c724c60b"),
                            ActorId = new Guid("5c56da82-871d-4993-b918-30238918232c"),
                            CharacterName = "Jack Dawson",
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8422),
                            Id = new Guid("780bd05d-244f-4343-a7a7-4b768064a626"),
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8422)
                        },
                        new
                        {
                            MovieId = new Guid("6b216128-bfe7-4e66-987f-2106c724c60b"),
                            ActorId = new Guid("f58bd65c-3508-46c3-9eb8-d55ac431db1e"),
                            CharacterName = "Rose DeWitt Bukater",
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8423),
                            Id = new Guid("41048d7b-7bc4-4c28-b0cf-3bc04b64e5b3"),
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8424)
                        });
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b5b7860b-c60b-40c9-83ad-634d83638cd7"),
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 848, DateTimeKind.Utc).AddTicks(9638),
                            RoleName = "Admin",
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 848, DateTimeKind.Utc).AddTicks(9639)
                        },
                        new
                        {
                            Id = new Guid("5d6358d1-a354-4b82-991c-6c035995d376"),
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 848, DateTimeKind.Utc).AddTicks(9648),
                            RoleName = "Staff Manager",
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 848, DateTimeKind.Utc).AddTicks(9649)
                        },
                        new
                        {
                            Id = new Guid("56c6e118-fd38-4feb-be1e-167e2e483682"),
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 848, DateTimeKind.Utc).AddTicks(9650),
                            RoleName = "Staff",
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 848, DateTimeKind.Utc).AddTicks(9650)
                        },
                        new
                        {
                            Id = new Guid("77c08f1c-9206-42d4-ab5d-722c7942701d"),
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 848, DateTimeKind.Utc).AddTicks(9652),
                            RoleName = "Customer",
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 848, DateTimeKind.Utc).AddTicks(9652)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("TheaterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TheaterId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Domain.Entities.Showtime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<int>("AvailableSeat")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("ShowtimeDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("RoomId");

                    b.ToTable("Showtimes");
                });

            modelBuilder.Entity("Domain.Entities.Theater", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TheaterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Theaters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("23b84abc-99f6-48c4-b77b-728b5b7cac28"),
                            CityId = new Guid("50a7f8e6-5f75-4a46-8cbb-27c3d3860f7f"),
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8327),
                            Location = "Số 1, Phố Ngô Quyền, Hà Nội",
                            TheaterName = "CGV Hà Nội",
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8328)
                        },
                        new
                        {
                            Id = new Guid("a69dc5c0-a91a-41c4-8366-e2a91669f2df"),
                            CityId = new Guid("50a7f8e6-5f75-4a46-8cbb-27c3d3860f7f"),
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8330),
                            Location = "Số 2, Phố Trần Duy Hưng, Hà Nội",
                            TheaterName = "Lotte Cinema Hà Nội",
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8330)
                        },
                        new
                        {
                            Id = new Guid("02b7a969-43a2-4625-965f-f74da2645878"),
                            CityId = new Guid("bc167d53-29dc-41ae-b8aa-b8c20c1d0ca7"),
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8332),
                            Location = "Số 10, Phố Nguyễn Huệ, Hồ Chí Minh",
                            TheaterName = "CGV Hồ Chí Minh",
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8332)
                        },
                        new
                        {
                            Id = new Guid("f75aa1fe-c36e-42c5-b99c-af89e5728e24"),
                            CityId = new Guid("bc167d53-29dc-41ae-b8aa-b8c20c1d0ca7"),
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8334),
                            Location = "Số 20, Phố Lý Tự Trọng, Hồ Chí Minh",
                            TheaterName = "BHD Star Cineplex",
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8334)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("ShowtimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("Id");

                    b.HasIndex("ShowtimeId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("Id");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("UUID()")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80f33926-0701-46c4-92c9-73e8989ae924"),
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8238),
                            Email = "admin@example.com",
                            IsBlocked = false,
                            PasswordHash = "8EleeVK4645feOy6QMfohV5xfgOyqt0Oc5kHGbJh4hM=",
                            PasswordSalt = "C16cVVOFWAJ6vtAQ0fHh0g==",
                            Phone = "1111111111",
                            RoleId = new Guid("b5b7860b-c60b-40c9-83ad-634d83638cd7"),
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8239),
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("02530f11-bfbb-411d-89ec-372a4a96810b"),
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8242),
                            Email = "manager@example.com",
                            IsBlocked = false,
                            PasswordHash = "S0xyLl7H2ph53W2CrDc/4Uu4IrlcltlVldY4l7TwJZw=",
                            PasswordSalt = "psJCzS+yvzIRRVd1kCJJrw==",
                            Phone = "2222222222",
                            RoleId = new Guid("5d6358d1-a354-4b82-991c-6c035995d376"),
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8242),
                            UserName = "staffmanager"
                        },
                        new
                        {
                            Id = new Guid("ee093080-7da4-4c02-8f60-5f0761ae89a2"),
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8248),
                            Email = "staff@example.com",
                            IsBlocked = false,
                            PasswordHash = "hINikXQdpCF3wQE8rO7vMh0X4+n6Bjl7Pf25d+T0xMg=",
                            PasswordSalt = "ZhyCaM4PJUw+3EcG2dXqlw==",
                            Phone = "3333333333",
                            RoleId = new Guid("56c6e118-fd38-4feb-be1e-167e2e483682"),
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8249),
                            UserName = "staff"
                        },
                        new
                        {
                            Id = new Guid("73ff0a84-b8dd-4ea8-9637-20a2f89e4805"),
                            CreatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8251),
                            Email = "customer@example.com",
                            IsBlocked = false,
                            PasswordHash = "86UgGt0G6cIcC5ERWWDBLe3vEZdetp6HePHEiKzn6yM=",
                            PasswordSalt = "vqnU5mqV9vUrQxMG338n/A==",
                            Phone = "4444444444",
                            RoleId = new Guid("77c08f1c-9206-42d4-ab5d-722c7942701d"),
                            UpdatedAt = new DateTime(2025, 5, 3, 6, 53, 15, 856, DateTimeKind.Utc).AddTicks(8252),
                            UserName = "customer"
                        });
                });

            modelBuilder.Entity("Domain.Entities.MovieActor", b =>
                {
                    b.HasOne("Domain.Entities.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Room", b =>
                {
                    b.HasOne("Domain.Entities.Theater", "Theater")
                        .WithMany("Rooms")
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("Domain.Entities.Showtime", b =>
                {
                    b.HasOne("Domain.Entities.Movie", "Movie")
                        .WithMany("Showtimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Room", "Room")
                        .WithMany("Showtimes")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Domain.Entities.Theater", b =>
                {
                    b.HasOne("Domain.Entities.City", "City")
                        .WithMany("Theaters")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Domain.Entities.Showtime", "Showtime")
                        .WithMany("Tickets")
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Showtime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Domain.Entities.Ticket", "Ticket")
                        .WithOne("Transaction")
                        .HasForeignKey("Domain.Entities.Transaction", "TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Actor", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Navigation("Theaters");
                });

            modelBuilder.Entity("Domain.Entities.Movie", b =>
                {
                    b.Navigation("MovieActors");

                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Room", b =>
                {
                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("Domain.Entities.Showtime", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Domain.Entities.Theater", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Tickets");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
